name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  # IMAGE_NAME: ghcr.io/devops-cloud-mm/myapp/myimage:latest
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_ZONE: us-central1-c

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 19
      - run: mvn clean install --batch-mode --errors --fail-at-end
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: demo2-0.0.1-SNAPSHOT.jar
          path: target/
  build-docker-image:
    name: build-docker
    needs: setup-build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Retrieve saved jar
        uses: actions/download-artifact@v3
        with:
          name: demo2-0.0.1-SNAPSHOT.jar
          path: target/

     #      - name: Checkout code
     #        uses: actions/checkout@v2

      - name: Login, Build and Push to Docker Hub
        id: login
        run: docker login -u ${{ secrets.DOCKER_USER  }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER  }}/spring-app:latest
      - name: Push the Docker image
        id: push
        run: docker push ${{ secrets.DOCKER_USER  }}/spring-app:latest
      
      
        #- name: Build and Push Docker image
        #env:
         # USERNAME: ${{ secrets.USERNAME }}
       #  PASSWORD: ${{ secrets.PASSWORD }}
       # run: |
        #  echo $PASSWORD | docker login ghcr.io -u $USERNAME --password-stdin
        #  docker build --tag $IMAGE_NAME .
         # docker push $IMAGE_NAME          

  deploy-to-gke:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
          ZONE_NAME: us-central1-c
        with:
          args: apply -f k8s/
